# Generated by Django 3.0.10 on 2020-09-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresses',
        ),
    ]
